### ISSUE TITLE
Grammer Issue: your

### ISSUE THREAD

**Issue by sfavorite** [susanBuck/dwa15-spring2016-notes#1]
In the lecture slide "01_Servers_and_Git/08_Live_domain_setup.md", the first sentence in the fourth paragraph should be changed from:

After your create your domain, find your DNS settings within your domain companies' control panel. 

to 

After **you** create your domain, find your DNS settings within your domain companies' control panel.

**Comment by susanBuck** [comment]
Fixed, thanks!
