### ISSUE TITLE
Upper Case

### ISSUE THREAD

**Issue by sfavorite** [susanBuck/dwa15-spring2016-notes#5]
In 13_View_and_Blade.md under the heading **Build your first View** the example has 

<!doctype html> but the W3C standard is to capitalize the word DOCTYPE.
From their website 

> The doctype declaration must be exact (both in spelling and in case) to have the desired effect...
[Doctype Declarations](https://www.w3.org/QA/2002/04/valid-dtd-list.html)

Hope these suggestions are helpful...I have found the class to be awesome!

**Comment by susanBuck** [comment]
Thanks! 

And yup, all of these catches are super helpful. I stop seeing certain mistakes after looking at the text so long, so outside perspectives are always welcome!
